/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.snakeUI;

import java.awt.event.KeyEvent;
import javax.swing.Box;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;



/**
 *
 * @author Jasmin Rose
 */
public class PlayerChoicePanel extends javax.swing.JPanel {
    
    FontChooser f = new FontChooser();
    String selected;
    Thread blinkThread1 = null, blinkThread2 = null;
    /**
     * Creates new form PlayerChoicePanel
     */
    public PlayerChoicePanel() {
        initComponents();
    }
    
    public void blinkText() {
        blinkThread1 = new Thread(new Runnable() {
            @Override
            public void run() {
                while(!blinkThread1.isInterrupted()) {
                    try {
                        returnVisible();
                        Thread.sleep(600L);
                    }
                    catch(InterruptedException e) {
                        blinkThread1.interrupt();
                        e.printStackTrace();
                    }
                }
            }

            public void returnVisible() {
                SwingUtilities.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        p1Label.setVisible(!p1Label.isVisible());
                    }
                });
            }
        });
        
        blinkThread2 = new Thread(new Runnable() {
            @Override
            public void run() {
                while(!Thread.currentThread().isInterrupted()) {
                    try {
                        returnVisible();
                        Thread.sleep(600L);
                    }
                    catch(InterruptedException e) {
                        e.printStackTrace();
                    }
                }
            }

            public void returnVisible() {
                SwingUtilities.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        p2Label.setVisible(!p2Label.isVisible());
                    }
                });
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        p1Label = new javax.swing.JLabel();
        p2Label = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 33, 0));
        setForeground(new java.awt.Color(0, 238, 0));
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(f.returnFont("joystix monospace.ttf", 16f));
        jLabel1.setForeground(new java.awt.Color(0, 238, 0));
        jLabel1.setText("Choose which Player: ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        p1Label.setFont(f.returnFont("joystix monospace.ttf", 16f));
        p1Label.setForeground(new java.awt.Color(0, 238, 0));
        p1Label.setText("> Player 1");
        add(p1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 36, -1, -1));

        p2Label.setFont(f.returnFont("joystix monospace.ttf", 16f));
        p2Label.setForeground(new java.awt.Color(0, 238, 0));
        p2Label.setText("> Player 2");
        add(p2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 59, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
        // TODO add your handling code here:
        blinkText();
        blinkThread1.start();
    }//GEN-LAST:event_formComponentAdded

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        
        try {
            if(key == KeyEvent.VK_DOWN) {
                blinkThread1.interrupt();
                p1Label.setVisible(true);
                blinkThread2.start();
            }
        }
        catch(Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_formKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel p1Label;
    private javax.swing.JLabel p2Label;
    // End of variables declaration//GEN-END:variables
}
